before_script:
  - "bundle exec rake refinery:testing:dummy_app > /dev/null"
script: "bundle exec rake spec"
notifications:
  email:
    - parndt@gmail.com
    - ugis.ozolss@gmail.com
    - joe@joesak.com
    - jamie@enmasse.com
env:
  - DB=postgresql
  - DB=mysql
matrix:
  allow_failures:
    - rvm: rbx
rvm:
  - 1.8.7
  - 1.9.3
  - rbx
  - jruby
